name: Run Python Tests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/ec2/etl/test-requirements.txt

      - name: Run tests with pytest
        run: |
          cd scripts/ec2/etl
          python -m unittest -v test-compute.SparkETLTestCase